name 'dev_box'
maintainer 'Jason Blalock'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dev_box'
long_description 'Installs/Configures dev_box'
version '0.1.0'

supports 'ubuntu'

depends 'apt', '~> 3.0.0'
depends 'chef-vault', '~> 1.3.3'
depends 'chruby_install', '~> 0.1.3'
depends 'docker'
depends 'git'
depends 'nvm', '~> 0.1.7'
depends 'sublime_text'
depends 'vim', '~> 2.0.1'
depends 'ruby_install'
